final jaJpTr = {
  'lang': '日本語',
  'appTitle': 'ロドス・アイランド　ターミナル',
  'networkUnreachable': 'ネットワークに接続されていません。インタネット接続を確認してください。',
  'remoteServerError': 'サーバーに接続できません。しばらくたってから再度お試しください。',
  'unexpectedError': 'あなたは私の華麗なる登場を台無しにした、ネズミ。',
  'failedToLoadData': 'データの読み込みに失敗しました。更新してから再度お試しください。',
  'connecting': 'ニューラルコネクターに接続中',
  'amiyaAttention': 'ドクター、終わってない仕事がたくさんありますから、まだ休んじゃだめですよ。',
  'itemsPage': '素材選択',
  'eventItems': 'イベントアイテム',
  'battleRecords': '作戦記録',
  'chips': 'SoC',
  'furniture': '家具',
  'materials': '素材',
  'uncategorized': '未分類',
  'stats': '統計データ',
  'stage': 'ステージ',
  'loots': 'ドロップ数',
  'samples': '周回数',
  'dropRate': 'ドロップ率',
  'expectedSanity': '期待理性',
  'normalDrop': '通常',
  'extraDrop': 'その他',
  'specialDrop': 'レア',
  'recruit': '公開求人',
};
