name: rhodersisland_terminal
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^0.6.7
  bloc: ^6.0.1
  cached_network_image: ^2.2.0+1
  connectivity: ^0.4.9
  dartz: ^0.9.1
  dio: ^3.0.10
  flutter_bloc: ^6.0.1
  freezed_annotation: ^0.11.0+1
  get_it: ^4.0.4
  injectable: ^1.0.4
  json_annotation: ^3.0.1
  loading_indicator: ^1.2.0
  shared_preferences: ^0.5.8
  sqflite: ^1.3.1
  styled_widget: ^0.2.1+2
  url_launcher: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^0.6.8
  build_runner: any
  freezed: ^0.11.5
  injectable_generator: ^1.0.4
  json_serializable: ^3.4.0
  pedantic: any

dependency_overrides:
  analyzer: '0.39.14'

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo/

