name: rhodes_island_terminal
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity: 3.0.6
  cupertino_icons: 1.0.3
  dartz: 0.10.0-nullsafety.2
  dio: 4.0.0
  flutter_screenutil: 5.0.0+2
  font_awesome_flutter: 9.1.0
  freezed_annotation: 0.14.2
  get: 4.1.4
  google_fonts: 2.1.0
  json_annotation: 4.0.1
  logger: 1.0.0
  moor: 4.3.2
  path: 1.8.0
  path_provider: 2.0.2
  pretty_dio_logger: 1.2.0-beta-1
  sqlite3_flutter_libs: 0.5.0
  supercharged: 2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.0.4
  freezed: 0.14.2
  json_serializable: 4.1.3
  moor_generator: 4.3.1
  pedantic: 1.11.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo/
    - assets/images/sprites/
