name: rhodes_island_terminal
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  auto_route: 0.6.9
  bot_toast: 4.0.0+1
  connectivity: 3.0.2
  cupertino_icons: 1.0.2
  dartz: 0.10.0-nullsafety.1
  dio: 4.0.0-beta7
  flutter_riverpod: 0.13.1
  flutter_screenutil: 5.0.0-nullsafety.9
  font_awesome_flutter: 9.0.0-nullsafety
  freezed_annotation: 0.14.0
  fuzzy: 0.4.0-nullsafety.0
  get_it: 6.0.0
  injectable: 1.2.0
  intl: 0.17.0
  json_annotation: 4.0.0
  kt_dart: 0.9.0-nullsafety.0
  loading_indicator: 1.2.0
  logger: 1.0.0-nullsafety.0
  path_provider: 2.0.1
  pretty_dio_logger: 1.2.0-beta
  shared_preferences: 2.0.4
  sqflite: 2.0.0+2
  url_launcher: 6.0.2
  uuid: 3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: 0.6.10
  build_runner: 1.11.5
  freezed: 0.14.0+1
  injectable_generator: 1.2.0
  json_serializable: 4.0.2
  pedantic: 1.11.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo/
    - assets/images/sprites/

flutter_intl:
  enabled: true
