name: rhodesisland_terminal
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  auto_route: ^0.6.9
  bloc: ^6.1.0
  cached_network_image: ^2.5.0
  connectivity: ^2.0.2
  dartz: ^0.9.2
  dio: ^3.0.10
  flutter_bloc: ^6.1.1
  flutter_riverpod: ^0.12.2
  flutter_screenutil: ^4.0.2+5
  font_awesome_flutter: ^8.11.0
  freezed_annotation: ^0.12.0
  get_it: ^5.0.4
  injectable: ^1.0.7
  intl: ^0.16.1
  intl_translation: ^0.17.10+1
  json_annotation: ^3.1.1
  loading_indicator: ^1.2.0
  logger: ^0.9.4
  oktoast: ^2.3.2
  shared_preferences: ^0.5.12+4
  sqflite: ^1.3.2+2
  styled_widget: ^0.2.2
  url_launcher: ^5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^0.6.10
  build_runner: ^1.10.13
  freezed: ^0.12.7
  injectable_generator: ^1.0.7
  json_serializable: ^3.5.1
  pedantic: ^1.9.2

dependency_overrides:
  analyzer: ^0.40.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo/

flutter_intl:
  enabled: true
